### ISSUE TITLE
Document mime type

### ISSUE THREAD

**Issue by rgrinberg** [nojb/ocaml-imap#18]
The `mime` type currently is a variant with a bunch of tuples as the arguments. It would be very helpful to have a little bit documentation as to what the fields are. In particular for \`Basic and \`Message.

**Comment by nojb** [comment]
Agreed.  I'll try to add some examples later.  Their naming and meaning actually comes from the MIME format (RFCs 2045-2049).  IMAP servers are supposed to be able to parse the MIME format so that one can, for example, request only a part of a message (say, a particular attachment) without having to download the whole thing.

**Comment by nojb** [comment]
Added some docs to the `mime` and `section` types.  Feel free to reopen if you like.  Thanks for reporting!
